<a href="https://colab.research.google.com/github/nunupradani/DataMiningUAS/blob/master/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB

In [2]:
data = pd.read_csv("/content/mmm.csv")
data.head()

,no,model,tahun,harga,transmisi,jarak_tempuh,bahan_bakar,pajak,mpg,ukuran_mesin
0,1,Mitsubishi,1870,290000000,Manual,27499,Petrol/Gasoline/Bensin,1800000,28,1.8
1,2,Honda civic type R,2022,400000000,Manual,20000,Diesel/Solar,150000,25,1.2
2,3,Toyota Innova V,2017,370000000,Manual,5000000,Petrol/Gasoline/Bensin,2000000,28,1.8
3,4,Toyota Agya,2020,136000000,Manual,24089,Petrol/Gasoline/Bensin,1725250,20,1.0
4,5,Toyota Agya,2017,200000000,Manual,19400,Petrol/Gasoline/Bensin,1200000,22,1.2

In [3]:
print(data.isnull().sum())

no              0
model           0
tahun           0
harga           0
transmisi       0
jarak_tempuh    0
bahan_bakar     0
pajak           0
mpg             0
ukuran_mesin    0
dtype: int64

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   no            160 non-null    int64
 1   model         160 non-null    object
 2   tahun         160 non-null    int64
 3   harga         160 non-null    int64
 4   transmisi     160 non-null    object
 5   jarak_tempuh  160 non-null    int64
 6   bahan_bakar   160 non-null    object
 7   pajak         160 non-null    int64
 8   mpg           160 non-null    int64
 9   ukuran_mesin  160 non-null    float64
dtypes: float64(1), int64(6), object(3)
memory usage: 12.6+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

In [6]:
for column in data:
  if data[column].dtypes == object:
    data[column] = enc.fit_transform(data[column])

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   no            160 non-null    int64
 1   model         160 non-null    int64
 2   tahun         160 non-null    int64
 3   harga         160 non-null    int64
 4   transmisi     160 non-null    int64
 5   jarak_tempuh  160 non-null    int64
 6   bahan_bakar   160 non-null    int64
 7   pajak         160 non-null    int64
 8   mpg           160 non-null    int64
 9   ukuran_mesin  160 non-null    float64
dtypes: float64(1), int64(9)
memory usage: 12.6 KB

In [8]:
data

,no,model,tahun,harga,transmisi,jarak_tempuh,bahan_bakar,pajak,mpg,ukuran_mesin
0,1,41,1870,290000000,1,27499,1,1800000,28,1.8
1,2,39,2022,400000000,1,20000,0,150000,25,1.2
2,3,85,2017,370000000,1,5000000,1,2000000,28,1.8
3,4,67,2020,136000000,1,24089,1,1725250,20,1.0
4,5,67,2017,200000000,1,19400,1,1200000,22,1.2
...,...,...,...,...,...,...,...,...,...,...
155,156,44,2022,224000000,1,21000,0,3200000,22,1.5
156,157,8,2018,148000000,1,20219,1,2000000,25,1.3
157,158,40,2016,287000000,1,8912,0,3200000,30,2.0
158,159,69,2011,295000000,0,28335,1,2000000,23,1.3
159,160,83,2017,208800000,1,10089,1,3800000,30,2.0

In [9]:
data.describe()

,no,model,tahun,harga,transmisi,jarak_tempuh,bahan_bakar,pajak,mpg,ukuran_mesin
count,160.000000,160.000000,160.000000,1.600000e+02,160.000000,1.600000e+02,160.000000,1.600000e+02,160.000000,160.000000
mean,80.500000,48.343750,2014.450000,1.686450e+08,0.875000,1.195561e+05,0.906250,2.610075e+06,25.275000,1.465625
std,46.332134,29.926334,12.120361,1.811359e+08,0.445099,3.964340e+05,0.292396,1.288941e+06,4.164767,0.412089
min,1.000000,0.000000,1870.000000,1.470000e+02,0.000000,1.020000e+03,0.000000,1.450000e+05,20.000000,1.000000
25%,40.750000,21.750000,2013.000000,1.072500e+08,1.000000,3.038400e+04,1.000000,2.000000e+06,22.000000,1.200000
50%,80.500000,51.500000,2016.000000,1.320000e+08,1.000000,7.029000e+04,1.000000,2.475000e+06,25.000000,1.300000
75%,120.250000,72.250000,2018.000000,1.863500e+08,1.000000,1.120000e+05,1.000000,3.200000e+06,25.000000,1.500000
max,160.000000,100.000000,2023.000000,2.147484e+09,2.000000,5.000000e+06,1.000000,9.431000e+06,42.000000,3.000000

In [11]:
trs_data = data.drop(columns='no')
trs_data.head()

,model,tahun,harga,transmisi,jarak_tempuh,bahan_bakar,pajak,mpg,ukuran_mesin
0,41,1870,290000000,1,27499,1,1800000,28,1.8
1,39,2022,400000000,1,20000,0,150000,25,1.2
2,85,2017,370000000,1,5000000,1,2000000,28,1.8
3,67,2020,136000000,1,24089,1,1725250,20,1.0
4,67,2017,200000000,1,19400,1,1200000,22,1.2

In [21]:
lbl_data = data['transmisi']
lbl_data.head()

0    1
1    1
2    1
3    1
4    1
Name: transmisi, dtype: int64

In [22]:
x_train,x_test,y_train,y_test=train_test_split(trs_data,lbl_data,test_size=0.9,random_state=500)
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

In [23]:
print('accuracy of Naive bayes Kontinu classifier on test set: {:.2f}'.format(classifier.score(x_test,y_test)))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
hasilpengujian = classification_report(y_test,y_pred)
print(hasilpengujian)

accuracy of Naive bayes Kontinu classifier on test set: 0.75
[[  2  22   0]
 [  7 106   0]
 [  3   4   0]]
0.75
              precision    recall  f1-score   support

           0       0.17      0.08      0.11        24
           1       0.80      0.94      0.87       113
           2       0.00      0.00      0.00         7

    accuracy                           0.75       144
   macro avg       0.32      0.34      0.33       144
weighted avg       0.66      0.75      0.70       144

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))